
export const URLS={
    HOME:'/home',
    LOGIN:'/login',
    REGISTER:'/register',
    RESOURCES:'/resources/',
    RESOURCES_MY:'/resources/my',
    RESOURCES_ADD:'/resource/add',
    RESOURCES_DETAILS:'/details/',
    RESOURCES_EDIT:'/resources/edit',
    COURSES:'/course/all/',
    COURSES_MY:'/course/my/',
    COURSES_OVERVIEW:'/course/preview/',
    COURSES_ID:'/course/trainings/',
    COURSES_LESSON:'/course/trainings/lesson/',
    COURSES_JOIN:`/course/join/`,
    PROFILE:`/profile`,
    TERMS:`/terms`,
    PRIVACY:`/privacy`,
    PRIVATE:`/private`,
}

export const APP_URLS = {
    HOME: '/home',
    LOGIN:'/login',
    REGISTER:'/register',
    LOGOUT: '/logout',
    RESOURCES: '/resources/:id',
    RESOURCES2: '/resources2/:id',
    DETAILS: '/details/:id',
    DETAILS2: '/details2/:id',
    RESOURCES_ADD: '/resource/add',
    RESOURCES_EDIT:'resources/edit/:id',
    PROFILE: '/profile/:id',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    COURSES: '/course/:id',
    COURSES_ALL: '/course/all/:id',
    COURSES_ALL2: '/course/all2/:id',
    COURSES_OVERVIEW:`/course/preview/:id`,
    COURSES_TRAININGS: '/course/trainings/:id/:courseTitle',
    COURSES_LESSON:'/course/trainings/lesson/:id/:topicTitle',
    COURSES_JOIN: '/course/join/:id',
    COURSES_MINE: '/course/mine/:id',
    PRIVATE:`/private`
  };

