

export const RESOURCE_VALIDATIONS={
    TITLE_MIN_LENGTH:10,
    TITLE_MAX_LENGTH:100,
    CONTENT_MIN_LENGTH:50,
    CONTENT_MAX_LENGTH:10000,
    IMAGEURL_MIN_LENGTH:10,
    IMAGEURL_MAX_LENGTH:200,
}


